title: Git testing page
author: Tahmid
email: myemail@myem.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  wow I can write descriptions!

# social links
twitter_username: tahmidstat
github_username:  tahmid-usc

show_excerpts: true # set to false to remove excerpts on the homepage
